package com.mshop;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.cloud.netflix.eureka.EnableEurekaClient;
import org.springframework.cloud.openfeign.EnableFeignClients;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn

@SpringBootApplication
@EnableEurekaClient
@EnableFeignClients
public class SecKillOrderServerApplication {

    public static void main(String[] args) {
        SpringApplication.run(SecKillOrderServerApplication.class, args);
    }

}
